### ISSUE TITLE
Lag shown by heapster to update metrics

### ISSUE THREAD

**Issue by shilpapadgaonkar** [openshift/origin-metrics#116]
Hello @mwringe ,
We found that heapster does not show the real time data and that there is usually a lag of ~ 3mins..
I have seen in some old heapster code (heapster.go)  the following content

argModelFrequency  = flag.Duration("model_frequency", 145*time.Second, "Frequency at which model will be updated. Applies only if use_model is true")

The latest heapster code  does not include this ModelFrequency part. I am not sure though which heapster version is used by the image: 

registry.access.redhat.com/openshift3/metrics-heapster:latest

Could this be the reason for the lag?

Regards,
Shilpa

**Comment by mwringe** [comment]
Where exactly are you seeing the lag? The console, direct api access to Heapster, direct api access to Hawkular Metrics, etc

A couple of things you may need to check:

1) that the clocks are synchronized on the nodes. If the nodes are running at slightly different times then the results will be off. This could account for the 3 minute delay you are seeing.

2) check that what is performing the metrics request also has its clock properly synchronized with the nodes. It looks like an older version of the console was using the browsers clock to perform queries, but its since been fixed (https://github.com/openshift/origin/commit/ee9b03c9500eb0124867adc30255853bd4ed7e87). This could also cause the issue you are seeing.

3) check the stats_resolution value for the Heapster rc (see https://access.redhat.com/solutions/2158481). If this value is set around a minute or more than you may be seeing a large delay because of this.

**Comment by mwringe** [comment]
Housekeeping to close older issues. If you think this issue is not resolved, please reopen it.
