### ISSUE TITLE
Parameterize memory footprint for Cassandra and Hawkular containers

### ISSUE THREAD

**Issue by csrwng** [openshift/origin-metrics#148]
For a non-production developer setup with 'oc cluster up', it should be possible to stand up metrics components with a reduced memory footprint so they can fit in a developer VM.

**Comment by csrwng** [comment]
@mwringe

**Comment by jsanda** [comment]
In addition to reducing the JVM heap size, there are other settings in cassandra.yaml that we can change to reduce the overall footprint. I have discussed this on the hawkular-dev mailing list. I'll repost the details here.

##### Disable hinted handoff
There is no need to run hinted handoff with a single node. Set the `hinted_handoff_enabled` property in cassandra.yaml to false.

##### Disable key and counter caches
This may decrease read performance but should reduce Cassandra’s overall memory usage. Set the `key_cache_size_in_mb` and `counter_cache_size_mb` properties in cassandra.yaml to 0.

##### Reduce the concurrent reads/writes
This will reduce the number of threads that Cassandra uses. Set the `concurrent_reads`, `concurrent_writes`, and `concurrent_counter_writes` properties in cassandra.yaml to 2.

##### Reduce file cache size
This is off-heap memory used for pooling SSTable buffers. For a 512 MB heap it will be 128 MB. Change the `file_cache_size_in_mb` property to 64.

##### Reduce memory used for memtables
This will increase the number of flushes which should be fine for write-heavy workloads. Change the `memtable_heap_space_in_mb` and `memtable_offheap_space_in_mb` properties to 64.

##### Reduce memory for index summaries
This defaults to a little over 25 MB. Change the `index_summary_capcaity_in_mb` property to 13.

##### Reduce the native transport threads
The native transport server will use a max of 128 threads by default. Change the `native_transport_max_threads` property to 32.

##### Disable thrift server
Set `start_rpc` to false which we should be doing all the time since we do not use thrift.

##### Tune compaction
Set `concurrent_compactors` to 1.
