### ISSUE TITLE
Example: How to retrieve metrics?

### ISSUE THREAD

**Issue by mmaier2** [openshift/origin-metrics#16]
Hi,

could you please give me (or link me to) an example how to read out gathered metrics. I'd assume I could use the REST API of Hawkular? But I'm always getting 403's. So some guidance would be great.
Thnx.
Markus

**Comment by mwringe** [comment]
You need to use the REST API of Hawkular, but with one extra change. The 403 error message should have specified that you are missing an authorization header.

If you want to access the Hawkular REST endpoint, you will need to do something like:

curl -H "Authorization: Bearer $TOKEN" -H "Hawkular-tenant: $PROJECT_NAME" -X GET https:/....

Where $PROJECT_NAME matches the name of the project you want to fetch metrics from. And $TOKEN matches a token provided by OpenShift which has access to the specified project.

**Comment by mmaier2** [comment]
Thanks for the help... Looks good. But we're running into the sample problems now like you  https://github.com/openshift/origin/issues/5294

**Comment by mwringe** [comment]
Yes, its an unfortunate issue with the certificates. openshift/origin#5294 does explain how to get around the issue for now by setting the hostname to the ip address

**Comment by mwringe** [comment]
The docs now contain a section on how to use the Hawkular API directly: https://github.com/openshift/origin-metrics/blob/master/docs/hawkular_metrics.adoc

Closing this issue. Please feel free to open any new issue you encounter when trying to access the Hawkular API.

As for the openshift/origin#5294 issue, that should be fixed in newer releases, but you may encounter a problem when performing an update from a previous release. Please see https://github.com/openshift/openshift-docs/pull/1290 for more information.
