### ISSUE TITLE
Support Prometheus

### ISSUE THREAD

**Issue by ibotty** [openshift/origin-metrics#184]
For organizations that already use prometheus, it makes sense to not support an additional metrics solution. What is required to _additionally_ support prometheus in a) the web gui and b) for auto-scaling, etc?

**Comment by jcantrill** [comment]
@jimmidyson Do you have any idea roughly what this would entail to use Prometheus as an alternate solution?

**Comment by mwringe** [comment]
Autoscaling only required Heapster and doesn't require historical storage. You don't need Hawkular Metrics or Prometheus to get autoscaling to work. Heapster can also be configured to store metrics directly to Prometheus if desired.

For the console, it directly accesses Hawkular Metrics to retrieve the metric data required. I don't believe there are any plans to support multiple alternative backends at this moment.

With Heapster's old timer ability, and I believe with some  work to have a common metric API in kubernetes, it may be possible in the future for the console go through Heapster or the API instead of accessing Hawkular Metrics directly. But I don't believe supporting this is on the radar yet.

**Comment by jimmidyson** [comment]
Assuming the web console has a pluggable API for querying the info it needs then it should be pretty easy to plug in Prometheus - it's got a great query language over HTTP so easy enough.

As @mwringe said, autoscaling is triggered from Heapster, not Hawkular. If you were looking to use Prometheus for that (which doesn't sound like such a bad idea to me) then I would discuss with Prometheus devs the best way to approach it. It could be done with alert manager, but that would need more discussion.

> Heapster can also be configured to store metrics directly to Prometheus if desired.

IIRC (could be wrong about this!) I'm not sure that Heapster can expose metrics for Prometheus to ingest currently & in fact that goes against Prometheus best practices so I wouldn't recommend going down that route.

**Comment by mwringe** [comment]
@jimmidyson hmm, you are correct, I don't know why I thought Heapster could use Prometheus to send metrics to, that doesn't even make sense with the Prometheus pull mechanism and Heapster using push. Thanks for the correction.

**Comment by Reamer** [comment]
Sorry for bumping
Is there some progress for supporting Prometheus as a replacement for Heapster, Cassandra and Hawkular.

**Comment by richm** [comment]
@theute
