### ISSUE TITLE
Browser CORS error for metrics

### ISSUE THREAD

**Issue by danni** [openshift/origin-metrics#220]
In Google Chrome with Openshift 1.3.0-rc1:

```
XMLHttpRequest cannot load https://metrics.openshift.badger/hawkular/metrics. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://openshift.badger' is therefore not allowed access.
```

**Comment by danni** [comment]
Weirdly the data requests (i.e. in the metrics tab) do return correct CORS headers.

**Comment by mwringe** [comment]
This sometimes occurs when the 'metricsPublicURL' is not properly configured in the master-config.yaml. Normally this occurs because the URL is not properly configured and its not pointing to the Hawkular Metrics endpoint, the Hawkular Metric endpoint itself does have CORS configured for it.

Can you please make sure your URL looks something like "https://hawkular-metrics.example.com/hawkular/metrics". The "/hawkular/metrics" is important to have at the end and people will sometimes forget to add it.

**Comment by danni** [comment]
I can confirm it's correct on all the masters.

Bit more information, since it turned out I was incredibly vague. This is on the "Overview" page for a project. On the "Metrics" tab and "Monitoring" page I get metrics correctly as I would expect.

**Comment by jcantrill** [comment]
@jwforres is there a master config setting that needs to be updated to allow CORs?

**Comment by mwringe** [comment]
@jcantrill the error is because Hawkular Metrics is not returning the proper cors response, but all endpoints should already have CORs enabled. So this is something which Hawkular Metrics needs to handle.

I believe though if you try and access an endpoint which does not exist, it will return a 404 error which does not have the CORs headers.

Do you know what version of OpenShift you are running and what version of Hawkular Metrics you are running? The version of Hawkular Metrics can be found from the /hawkular/metrics/status page

**Comment by danni** [comment]
It's all the v1.3.0-rc1 docker images.

**Comment by henderb** [comment]
Is the CORs header enabled for the `/hawkular/metrics` page? The openshift overview seems to try that url first and switches the pod view away from metrics if that one fails. https://github.com/openshift/origin-web-console/blob/master/app/scripts/services/metrics.js#L88

I'm seeing the overview decide to not show metrics on Origin 1.3.1 with hawkular `{"MetricsService":"STARTED","Implementation-Version":"0.21.5.Final","Built-From-Git-SHA1":"e779588593f13224225356a94f1d8642fbccb30f"}`

Metrics tabs on individual pages work.

**Comment by mwringe** [comment]
the CORs header should be enabled for the /hawkular/metrics page.

The 0.21.5.Final version of Hawkular Metrics does not correspond to the version meant for OpenShift 1.3.1. I suspect your images are tagged with 'latest' when they should be tagged with 'v1.3.1'.

Since it works in the individual pod page, this is most likely an issue with the console.

@spadgett any idea here?

**Comment by spadgett** [comment]
@danni Are you able to load the metrics URL directly if you paste it in the location bar?

https://metrics.openshift.badger/hawkular/metrics

Any chance you have an ad blocker installed in your browser? Some ad blockers match `/metrics/metrics`, which in the URL we use for the overview, but not on the pod metrics page. It can look like a CORS error since the preflight request fails.

**Comment by danni** [comment]
I do have an adblocker installed. Interestingly, after I reinstalled the metrics (because my Cassandra melted and wouldn't recover the schema after I cleaned it) it started working fine. So I've lost the ability to debug what might have happened. I think we can probably close this?

**Comment by jcantrill** [comment]
@danni please close if you feel that is appropriate.

**Comment by steven166** [comment]
I'm encountering the same problem where Hawkular is giving CORS problems on the dashboard. This only happens in Chrome, but not in Chrome incognito. I'm running Openshift v1.4.1 with metrics v1.4.1 installed

Normal chrome http request:
```
**Request**
Request URL:https://metrics-dev.maxxton.com/hawkular/metrics
Request Method:GET
Status Code:200 OK
Remote Address:192.168.252.210:443
Referrer Policy:no-referrer-when-downgrade

**Request Headers:**
Accept:application/json, text/plain, */*
Origin:https://openshift-dev.maxxton.com:8443
Referer:https://openshift-dev.maxxton.com:8443/console/project/mxtf/overview
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

**Response Headers:**
Accept-Ranges:bytes
Content-Length:1600
Content-Type:text/html
Date:Wed, 19 Apr 2017 13:38:35 GMT
Last-Modified:Tue, 08 Nov 2016 14:21:12 GMT
Server:WildFly/10
X-Powered-By:Undertow/1
```

Incognito chrome http request:
```
**Request**
Request URL:https://metrics-dev.maxxton.com/hawkular/metrics
Request Method:GET
Status Code:200 OK
Remote Address:192.168.252.210:443
Referrer Policy:no-referrer-when-downgrade

**Request Headers:**
Accept:application/json, text/plain, */*
Accept-Encoding:gzip, deflate, sdch, br
Accept-Language:nl-NL,nl;q=0.8,en-US;q=0.6,en;q=0.4
Connection:keep-alive
Host:metrics-dev.maxxton.com
Origin:https://openshift-dev.maxxton.com:8443
Referer:https://openshift-dev.maxxton.com:8443/console/project/mxtf/overview
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

**Response Headers:**
Access-Control-Allow-Credentials:true
Access-Control-Allow-Headers:origin,accept,content-type,hawkular-tenant,authorization
Access-Control-Allow-Methods:GET, POST, PUT, DELETE, OPTIONS, HEAD
Access-Control-Allow-Origin:https://openshift-dev.maxxton.com:8443
Access-Control-Max-Age:259200
Cache-control:private
Content-Length:132
Content-Type:application/json
Date:Thu, 20 Apr 2017 12:35:22 GMT
Server:WildFly/10
Set-Cookie:0c90df416451b6e4cbf092da0788a52a=a47b7ed297abddf4fc46b666d3bb05db; path=/; HttpOnly
X-Powered-By:Undertow/1
```

**Comment by mwringe** [comment]
In incognito mode, a big difference is that plugins are not running. If you disable your browser plugins, does this make a difference? Trying to figure out what would be causing this problem.

Some ad blockers are blocking anything with "/metrics/metrics" in it, and this is unfortunately matches some of the url paths we have tried. We have tried to get them to modify their filter, but they are incapable of making a change.

**Comment by henderb** [comment]
Is the metrics page cached in your browser? My problem seemed to be that on updates/reinstalls, it would get cached and stop working for a while or until I deleted the cache for the page.

**Comment by steven166** [comment]
It was indeed a caching issue. Chrome has cached that request and wouldn't let it go until I cleared all my browser cache. Thanks!

**Comment by spadgett** [comment]
@mwringe We're testing the `/hawkular/metrics` URL just to check that Hawkular is there before making more requests. Is there a better endpoint to use for health? `Cache-control: private` won't prevent the browser from caching the response.

**Comment by mwringe** [comment]
The 'hawkular/metrics' or 'hawkular/metrics/status' are probably good endpoints to check.

The service shouldn't even have any pods unless one of the metric pods satisfies the readiness probe which checks a value from that endpoint.

**Comment by bortek** [comment]
I had the same problem after I upgraded from 3.5 to 3.6. It was working in Incognito mode and not in normal  as @steven166 reported. When clearing caches it started to work. It is kinda not nice to tell the end users to clear caches after the upgrade.

**Comment by AlbertoPeon** [comment]
I am also seeing this after upgrading from 1.5 to 3.6 - from an incognito session, metrics work and display but no from a normal window. This happens with Chrome, Firefox and Safari. 

Checking with the Chrome console I see the same thing as reported by @steven166 in https://github.com/openshift/origin-metrics/issues/220#issuecomment-295723738, exactly the same headers missing when using a normal window.

In my case it does not seem to be a caching/plugins issue as with a clean browser I see the same problem.

Do you have an idea of what might be happening? Thanks!
