### ISSUE TITLE
Change in response format

### ISSUE THREAD

**Issue by shilpapadgaonkar** [openshift/origin-metrics#256]
Hello,

In older versions if there were no metrics available the response used to look like  
[{"start":1478690267430,"end":1478719067430,"min":"NaN","avg":"NaN","median":"NaN","max":"NaN","percentile95th":"NaN","samples":0,"empty":true}]

Now it just looks as below:
[{"start":1478690297134,"end":1478719097134,"empty":true}]

Is this understanding correct?

Is cpu/usage_rate not valid anymore in 3.3 release?

hawkular/metrics/counters/data?tags=descriptor_name:cpu/usage_rate&buckets=1&start=-10mn&end=now

I have a ticket also open in ose supprort site - https://access.redhat.com/support/cases/#/case/01736286

https://github.com/openshift/origin-metrics/issues/255

Regards,
Shilpa

**Comment by mwringe** [comment]
> In older versions if there were no metrics available the response used to look like
> [{"start":1478690267430,"end":1478719067430,"min":"NaN","avg":"NaN","median":"NaN","max":"NaN","percentile95th":"NaN","samples":0,"empty":true}]
> 
> Now it just looks as below:
> [{"start":1478690297134,"end":1478719097134,"empty":true}]
> 
> Is this understanding correct?

Yes, this is correct. If there is no values for the metric for the bucket, then 'empty' will be 'true' and there is no values for min/avg/median/max/percentile95th/etc.

It makes more sense to send it this way (we don't need to continue to send those values which are going to be empty or useless anyways).

If your bucket does contain a sample, you will get back the properly filled out response.

> Is cpu/usage_rate not valid anymore in 3.3 release?
> 
> hawkular/metrics/counters/data?tags=descriptor_name:cpu/usage_rate&buckets=1&start=-10mn&end=now

The cpu/usage metric is a counter type metric, the cpu/usage_rate is a gauge type metric. It looks like you are using the counter endpoint instead of the gauge one. You will need to update your url for this to work.
