### ISSUE TITLE
hawkular rest api problem

### ISSUE THREAD

**Issue by yeganx** [openshift/origin-metrics#299]
hi
I want access to project metrics in my openshift project named : test
my metrics tab is working .
 oc get pods
NAME                             READY     STATUS      RESTARTS   AGE
hawkular-cassandra-1-gmdds       1/1       Running     0          20h
hawkular-metrics-y976l           1/1       Running     1          20h
heapster-2ax46                   1/1       Running     1          20h
metrics-deployer-2ih9y           0/1       Completed   0          20h
  
problem is I can not access rest api 

curl -H "Authorization: Bearer q3Z76It9XqcU_boMGIRdiv8kWS4whA0vSHfJe4W-l2s" -H "Hawkular-Tenant: test" -X GET https://metrics.10.1.2.2.xip.io/hawkular/metrics/metrics | python -m json.tool

out put is : 

curl: (60) Peer's certificate issuer has been marked as not trusted by the user.
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
No JSON object could be decoded

**Comment by mwringe** [comment]
Its because your curl command does not view the Hawkular Metrics certificate as being valid. By default it will be using the router's default certificate, which is self signed and will not be viewed as valid to any tool or web browser.

If you are providing your own certificate for the route and not using the default one, its because your certificate is not signed by a trusted CA.

If you want the certificate to be viewed as valid by default by things accessing it, you will need to sign the certificate with a trusted CA.

If you want to by-pass the security check that curl is using, you can do so by adding -k or --insecure to your command.

If you want to have curl trust this connection even with a self signed certificate, you will need to use --cacert and point that to the CA file used to sign the route's certificate.
