### ISSUE TITLE
metrics-deployer  pod has metric config options appended to hostname

### ISSUE THREAD

**Issue by skynardo** [openshift/origin-metrics#313]
New origin 1.4.1 install metrics-depoyer pod in error. When I describe the pod I see that the HAWKULAR_METRICS_HOSTNAME has the correct Hostname but also includes a string of Metrics deployment options which causes the ansible installer Validate Hostname to fail. 

Here is the HAWKULAR_METRICS_HOSTNAME from a describe pod:
HAWKULAR_METRICS_HOSTNAME:        hawkular-metrics.origin.ugcloud.local,USE_PERSISTENT_STORAGE=true,DYNAMICALLY_PROVISION_STORAGE=false,METRIC_DURATION=7,METRIC_RESOLUTION=10s,MODE=deploy

Any ideas what might be causing this?

**Comment by mwringe** [comment]
Its because you can no longer enter parameters like this. They changed the behaviour so that comma separated lists are no considered to be separate entries but one long string (which is good news if you want to include commas in a parameter, but bad news if you are trying to use old commands).

This is something which changed in OpenShift and not something specific to the metrics components.

What you need to do now is to use is "-p key1=value1 -p key2=value2 ...."

Eg:
oc process -f metrics.yaml -p HAWKULAR_METRICS_HOSTNAME=hawkular-metrics.example.com -p USE_PERSISTENT_STORAGE=true -p MODE=redeploy | oc create -f -

**Comment by skynardo** [comment]
I am running the full ansible installer using config.yml which is trying to install metrics.  Maybe there is an issue with the version of ansible-playbooks I am running then?

**Comment by mwringe** [comment]
Are you sure you are using the 1.4 version of the ansible playbook?
