### ISSUE TITLE
Ability to run a debug script on startup of containers

### ISSUE THREAD

**Issue by mwringe** [openshift/origin-metrics#314]
We have run into a few situations where we have issues which are not reproducible in our own environments. but they are reproducible in user environments.

In some of these situations, we have have an idea about what the cause is and how to test if a change or workaround will fix the issue for the users.

But, in some of these situations, the change required would either require modifying a file in the container or adding in an extra file. This type of change would normally require a new container to be built and pushed out to a docker registry, or have the container packaged in a tar and sent to the user.

This is really not an ideal situations.

Since we use scripts to start our containers, what we could potentially do to have the script look for a particular file, and if the file exists, it could be executed as the first step in our scripts. This script (as well as extra files) could be loaded into the container via a configmap.

Since this is a script, it could be used to copy the extra files to somewhere else on the files system, or append an extra line to an existing property file.

Note: we can technically do this today by modifying the pod's configuration. All that we would need to do is to load the script in a configmap, and then modify the start command for the pod to be the new script which is loaded. After this new script is executed, it could then just run the original command for the container. But this is a lot more awkward than just providing a default test script which could be run.

Note2: we only want to have this for debug situations where we cannot reproduce ourselves, and to verify the issue with users before pushing out an updated container. We don't want this to be used in normal situations.

**Comment by mwringe** [comment]
@jcantrill any thoughts?

**Comment by jcantrill** [comment]
I think anything we can do to simplify debugging the logging stack is reasonable.  It is a complicated integration that can fail at any number of integration points.  In the logging stack we have started investigation of diagnostic tools that will be packaged with the image as well as introducing utilities that we can ask users to run to assist in providing feedback.  Per my comment from our architecture meeting, my only add would be to make sure we introduce proper logging.  We should be able to identify that we are in a 'debug' mode so that users do not abuse the functionality and we are left constantly investigating issues that are of their own making.

**Comment by mwringe** [comment]
Yeah, we need to indicate that we are in a 'debug' or 'test' mode. Would having this in the logs be sufficient? Or should we have some other indicator as well?

**Comment by jcantrill** [comment]
I don't know how else we would indicate it so I think logs would be sufficient.  At  some point I would expect we might ask for logs and it should be fairly obvious the image is in this state.  Maybe even a marker file too where its existence would imply at some point it was put into debug state
