### ISSUE TITLE
tags and label based search 

### ISSUE THREAD

**Issue by shilpapadgaonkar** [openshift/origin-metrics#34]
Hello,

I am trying to retrieve metrics based on labels. I want to make sure that it only returns me records when all search criterias (specified as part of tags) match.

For eg, in the case below, I want to make sure that if my label "labels:metrics-infra:hawkular-cassandra" is not found, it should not return me anything.

However in my request, even if the label part doesn't match,or I give some incorrect label, it returns me data(i think based on just the tag tags=descriptor_name:cpu/usage).
Is there a way to avoid this?

curl -H "Authorization: Bearer itvTorMGGX5tg1RuBFa0dErA3NdEN8ZhBeGGJ_byfbo" -H "Hawkular-tenant: ametrics" -H "Accept: application/json" -X GET https://172.30.231.219/hawkular/metrics/counters/data?'tags=descriptor_name:cpu/usage&tags=container_name:hawkular-cassandra&tags=labels:metrics-infra:hawkular-cassandra&bucketDuration=8h' --insecure

Thanks,
Shilpa

**Comment by mwringe** [comment]
Sorry for taking so long to get back to you.

I believe the issue is that you have two tags query strings, when there should only be one. You should be using a `,` in between instead of new tags query strings

To perform a query based on the tags where you want both tags to match, your query string should look something like this:

&tags=container_name:hawkular-cassandra,labels:metrics-infra:hawkular-cassandra

Note that the above only works if the tags exactly match what is specified. So if the labels contain more than just `metrics-infra:hawkular-cassandra` it wont match.

They do take regular expressions though:

?tags=container_name:hawkular-.\*,labels:.\*metrics-infra.\*

There is now an example now in the documents on how to perform a tag based query based on two tags: https://github.com/openshift/origin-metrics/blob/master/docs/hawkular_metrics.adoc#querying-based-on-tag
Examples based on reg expressions will be added shortly

Please let me know if this works for you or if the docs and explanations are sufficient

**Comment by mwringe** [comment]
Any update on this? Or something we can help out more with?

**Comment by shilpapadgaonkar** [comment]
Yes thanks, this worked for me.
