### ISSUE TITLE
Supported way to use external Cassandra?

### ISSUE THREAD

**Issue by ksurent** [openshift/origin-metrics#348]
Hi,

I was wondering if there's an easy&supported way of making Hawkular use external Cassandra. By external I mean something that is not deployed using the scripts from this repo. It can still run inside the same OpenShift cluster, or a different cluster, or even just bare metal.
I skimmed through the installation scripts and it appears that it's expected that Cassandra is available in the same cluster under a certain Service. Please correct me if I'm wrong.

If not, do you think it's something you'd want to support? Consider use cases where there's already a streamlined way of setting up Cassandra (either containerised or bare metal) and users prefer to use that instead of deploying it with Hawkular.

**Comment by jsanda** [comment]
I am not sure what changes would be required as I have not looked into it,
but I think it is a  good idea.

**Comment by jpkrohling** [comment]
This would require some work on the side of whoever is installing, specially to secure the communication between Hawkular and Cassandra. Those are the items I could think of, to use an external Cassandra:

- [ ] Externalize the properties `hawkular.metrics.cassandra.nodes` (like `METRIC_DURATION`)
- [ ] Add a flag to the playbook, to skip the Cassandra parts

Then, the admin installing Cassandra/Hawkular would need to:

- [ ] Add Cassandra's signer CA into the Hawkular's secret store
- [ ] Add Hawkular's cert into Cassandra's client trust store

These steps are currently being done here:
(like this: https://github.com/openshift/origin-metrics/blob/master/deployer/scripts/hawkular.sh#L25-L68)

**Comment by mwringe** [comment]
Yeah, as mentioned, you can't really do it easily today. We could update our ansible playbooks to allow someone to specify an external Cassandra to connect to (eg URL + ca certificate). I don't think this would be too difficult to add.

We accept PRs if you would like to add in this feature :)

Otherwise it might be better to add a request via a bugzilla at https://bugzilla.redhat.com (against the 'OpenShift Container Platform' product and the 'metrics' component). There are more people monitoring the bugzillas than there are people who are monitoring these issues.
