### ISSUE TITLE
should suggest when processing template to include master_url

### ISSUE THREAD

**Issue by thoraxe** [openshift/origin-metrics#38]

**Comment by mwringe** [comment]
Is there a specific situation where you are seeing the need to set the master_url? Under normal situations, I don't think this should be changed. If you are requiring to specify this, I would be greatly interested. 

I would almost consider it an invalid installation if https://kubernetes.default.svc:443 cannot be resolved.

**Comment by thoraxe** [comment]
The docs tell you to set the master URL. The URL of my master is https://ose3-master.example.com:8443

When I was trying to get it set up this morning, @jwforres said that I need to set it. So, it appears that there is some misunderstanding about when you need to use this parameter versus when you do not need to use it.

**Comment by mwringe** [comment]
@jwforres do you know why this needs to be set? https://kubernetes.default.svc/ should be a valid

**Comment by mwringe** [comment]
I have seen a problem with our QE guys requiring to set the master URL, in that case it was purely a problem with their install.  https://kubernetes.default.svc/ was resolvable, but the certificates it was using was incorrectly configured and did not include kubernetes.default.svc as a hostname

**Comment by jwforres** [comment]
I believe erik had to set the master URL somewhere in the metrics set up
because he was hitting a CORS issue with the web console talking to the
metrics endpoint.  Is that what you are referring to?  Although I think
that ended up being because the assetConfig metricsPublicURL was not
configured correctly.  @thoraxe did you try taking that master url config
away after you got the asset config set up right?

**Comment by thoraxe** [comment]
I'm going to be rebuilding tomorrow so I'll try to remember to double check without setting that URL.

**Comment by thoraxe** [comment]
Sorry this took me a while to get back to. When I did the install the second time I did not explicitly set the URL, and it all worked, so I think we're good.

There is a "problem" in that the fluentd/logging stuff also kinda has some URL settings so it's just weird that one of the two "features" doesn't require it while the other one does...

**Comment by mwringe** [comment]
There are two different master endpoints. One which is for internal components (MASTER_URL), and another which is exposed externally (PUBLIC_MASTER_URL).

The MASTER_URL has a known default url in which it should be accessible from.

The PUBLIC_MASTER_URL is something which is required to be set. This is the url which can be accessible from outside of the OpenShift system.

The metrics components only need to use the MASTER_URL, while the logging components need to also used the PUBLIC_MASTER_URL. The logging components need the PUBLIC_MASTER_URL since you need to connect to it from a browser for oauth purposes.

**Comment by mwringe** [comment]
Closing this issue for now as I believe its been described and is no longer causing any more confusion. If you think this still needs to be addressed, please reopen this issue.
