### ISSUE TITLE
Hawkular-Cassandra pod consuming all memory assigned to it

### ISSUE THREAD

**Issue by karanatree** [openshift/origin-metrics#411]
--- Issue in Brief ---
In our production environment, the hawkular-cassandra pod is always consuming all the memory assigned to it.

--- Details ---

- Memory available to pod = 8GB
- Heap Configuration = 2 GB (1/4th of Memory)
Data Size = 70GB (62GB data, 8GB commitlog)
- THP (Transparent HugePages is enabled on the node on which this container runs) = Could this be using the memory?
- Docker Stats shows around 2.7GB of memory used. Since Docker Stats doesn't show cache memory, I suspect the extra memory being used is OS page cache.

This is causing issues in retrieving metrics data and showing it on the openshift dashboard.
Any suggestions why this is happening?

**Comment by jsanda** [comment]
Are you certain about what the problem is? Cassandra uses memory-mapped files for many things, namely SSTables. By doing so, it defers to the OS about what and when to flush to disk. You should expect your OS page cache to getting utilized. If something else needs memory, the OS will remove something from the cache if necessary. If the page cache is **not** get used, then I would worry about performance problems as you are likely to be hitting disk more.
