### ISSUE TITLE
Is this code supposed to do anything?  As far as I can tell, this JVM_OPTS env var is not being leveraged.

### ISSUE THREAD

**Issue by mshutt** [openshift/origin-metrics#424]
Is this code supposed to do anything?  As far as I can tell, this JVM_OPTS env var is not being leveraged:

https://github.com/openshift/origin-metrics/blob/903e5baed43c3a053b1fec28869588ae6f65402b/cassandra/cassandra-docker.sh#L190

The reason I ask is that I'd like to be able to get some metrics from the hawkular cassandra instance for the purpose of monitoring the health of the backing store for heapster/hawkular within our OpenShift Origin 3.9 infrastructure.  We're currently checking hawkular-api via the /hawkular/metrics/status URI which does have a portion of the output dedicated to the Cassandra status (e.g. "Cassandra":"up"), but I'd like something a bit... deeper... And I did see that the issue that existed with 3.7.0/3.7.1 containers wherein the case of True/False was an issue ("x${ENABLE_PROMETHEUS_ENDPOINT,,}" = "xtrue" ) was fixed and this env var is set, but the java args do not include the arguments to enable prometheus on 7575/tcp.

**Comment by matihost** [comment]
hi, I encountered the same problem (OKD 3.9.0)

**Workaround:**
I tried to workaround the problem by changing the values in inventory:
```
openshift_metrics_cassandra_enable_prometheus_endpoint='true'
openshift_metrics_hawkular_enable_prometheus_endpoint='true'
```

With that ReplicaControllers for C*  and Hawkular Metrics have  env variable:
```
        - name: ENABLE_PROMETHEUS_ENDPOINT
          value: "true"
```
instead of "True"

After that:
```
oc rsh hawkular-metrics-8mrqn
sh-4.2$ curl http://localhost:7575/metrics
# HELP jmx_scrape_duration_seconds Time this JMX scrape took, in seconds.
# TYPE jmx_scrape_duration_seconds gauge
jmx_scrape_duration_seconds 1.38553E-4
# HELP jmx_scrape_error Non-zero if this scrape failed.
# TYPE jmx_scrape_error gauge
jmx_scrape_error 0.0
# HELP jvm_classes_loaded The number of classes that are currently loaded in the JVM
# TYPE jvm_classes_loaded gauge
jvm_classes_loaded 9864.0
# HELP jvm_classes_loaded_total The total number of classes that have been loaded since the JVM has started execution
```

**What is wrong:**
The defaults are wrong and/or ansible inserting Yaml boolean instead of  its string representation.

The reason is 
https://bugzilla.redhat.com/show_bug.cgi?id=1508496
and https://bugzilla.redhat.com/show_bug.cgi?id=1571641
but i see it is still not solved in master...

Essentially the default value is 'True'  for ansible variables:
https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_metrics/defaults/main.yaml#L72 

they are literally copied to:
https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_metrics/templates/hawkular_cassandra_rc.j2#L63
https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_metrics/templates/hawkular_metrics_rc.j2#L71

While C* and Hawkular scripts compare with  string 'true' 
https://github.com/openshift/origin-metrics/blob/master/hawkular-metrics/standalone.conf#L61
https://github.com/openshift/origin-metrics/blob/master/cassandra/cassandra-docker.sh#L189
(so xTrue != xtrue)

So by default it is ... disabled.
